name: Android Build (with Gradle wrapper)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup JDK 21
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 21

    - name: Setup Android SDK and accept licenses
      uses: android-actions/setup-android@v3
      with:
        accept-android-sdk-licenses: true
        packages: build-tools;34.0.0,platform-tools,platforms;android-34

    - name: Generate Gradle Wrapper (if missing)
      run: gradle wrapper

    - name: Grant execute permission to gradlew
      run: chmod +x gradlew

    - name: Build Debug APK
      run: ./gradlew assembleDebug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-debug.apk
        path: app/build/outputs/apk/debug/app-debug.apk
