name: Android CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # نصب خودکار JDK + Android SDK + Gradle
      - name: Set up Android
        uses: android-actions/setup-android@v2

      # کامپایل با Gradle
      - name: Build APK
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: wrapper # از gradle-wrapper.properties استفاده می‌کند
          arguments: assembleDebug --stacktrace --no-daemon

      # آپلود APK
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/*.apk
