name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # نصب Android SDK + NDK + CMake
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
        with:
          sdk-platform: android-34
          sdk-build-tools: 34.0.0
          ndk-version: '25.1.8937393'
          cmake-version: '3.22.1'

      # تنظیم JDK 17
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # نصب Gradle 8.4 (بدون نیاز به gradlew)
      - name: Install Gradle
        run: |
          wget https://services.gradle.org/distributions/gradle-8.4-bin.zip -P /tmp
          unzip -q /tmp/gradle-8.4-bin.zip -d /tmp/
          echo "$/tmp/gradle-8.4/bin" >> $GITHUB_PATH

      # ساخت پروژه با Gradle
      - name: Build with Gradle
        run: |
          gradle --version
          gradle assembleDebug --no-daemon

      # آپلود APK
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/*.apk
          retention-days: 5
