name: Android CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # نصب Android SDK + JDK
      - name: Setup Android
        uses: android-actions/setup-android@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # ساخت با Gradle 8.4
      - name: Build
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 8.4
          arguments: assembleDebug --stacktrace --no-daemon

      # آپلود APK
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/*.apk
